export ZSH=/root/.oh-my-zsh
ZSH_THEME="gnzh"
plugins=( git cp pip zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
alias i="sudo apt install"
alias r="sudo apt remove"
alias si="sudo snap install "
alias u="sudo apt dist-upgrade && sudo apt update"
alias fix="sudo apt-get autoremove && sudo dpkg --configure -a && sudo apt -f install && sudo apt-get --fix-broken inst"
alias ..="cd .."
alias ...="cd ../.."
alias c='clear'
alias r='env zsh -l'
alias cp="cpv --progress"
alias motion="ssh -R 9020:localhost:8765 serveo.net"
alias ng80="killall ngrok && sed -i 's/8765/80/g' /home/mirage/.ngrok2/ngrok.yml && ngrok start --all"
alias ng8765="killall ngrok && sed -i 's/80/8765/g' /home/mirage/.ngrok2/ngrok.yml && ngrok start --all"
alias ngrc="sudo mcedit /home/mirage/.ngrok2/ngrok.yml"
alias webui="node webui-aria2-master/node-server.js"
alias $d="/home/mirage/downloads/"
alias m='mcedit'
