#!/bin/bash

EDITOR=vim
PASSWD=/etc/passwd
RED='\033[0;0;31m'
STD='\033[0;0;39m'
WTE='\033[0;37m'
pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}
YTB(){
	echo "          mirage Studio"

	echo "For audio only press 1"
	echo "For video 360p press 2"
	echo "For video 480p press 3"
	echo "For video 720p press 4"
	echo "For video 1080p press 5"

	command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'
	read option

	if [ "$option" -eq "1" ]
	then
	    echo "$command 140" > ~/.config/youtube-dl/config
	youtube-dl -x --audio-format mp3 --external-downloader aria2c --external-downloader-args '-c -j 16 -x 16 -s 16 -k 1M' $1
	mv *.mp3 /storage/downloads


	elif [ "$option" -eq "2" ]
	then
	    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
	     youtube-dl --external-downloader aria2c --external-downloader-args '-c -j 16 -x 16 -s 16 -k 1M' $1
	     mv *.mp4 /storage/downloads
	     mv *.mkv /storage/downloads
	     mv *.avi /storage/downloads

	elif [ "$option" -eq "3" ]
	then
	    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
	    youtube-dl --external-downloader aria2c --external-downloader-args '-c -j 16 -x 16 -s 16 -k 1M' $1
	     mv *.mp4 /storage/downloads
	     mv *.mkv /storage/downloads
	     mv *.avi /storage/downloads

	elif [ "$option" -eq "4" ]
	then
	    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
	    youtube-dl --external-downloader aria2c --external-do
	    fi
	pause
	}

show_menus() {
        clear
        echo "~~~~~~~~~~~~~~~~~~~~~"
        echo " M A I N - M E N U"
        echo "~~~~~~~~~~~~~~~~~~~~~"
        echo -e "1. Facebook DL    \t \t3. Youtube DL \n2. Internet DL   \t \t4. ${RED}Exit${WTE}"
	}

read_options(){
        local choice
        read -p "Enter choice [ 1 - 4] " choice
        case $choice in
                1) python FB_DL $1 ;;
                2) aria2c -c -x=16 $1 ;;
                3) YTB ;;
                4) exit 0;;
                *) echo -e "${RED}Error...${STD}" && sleep 2
        esac
}

trap '' SIGINT SIGQUIT SIGTSTP

while true
do
        show_menus
        read_options
done
